[c_hybrid_mpi+openmp] Allow passing number of steps from command line
UCL-RITS/pi_examples pull request #26
Opened 2024-11-27 18:21 UTC by giordano

2024-11-28 17:48 UTC, ikirker requested changes

2024-11-28 17:48 UTC, ikirker commented on c_hybrid_mpi+openmp_dir/run.sh
> +mpirun ./hybrid_pi ${@}
Please:

 - ❌ `${@}`
 - ✅ `"${@}"` or `"$@"`

(Unless, in a particular case, there's a good reason to do otherwise and disable that shellcheck case.)

2024-11-28 19:08 UTC, giordano commented on c_hybrid_mpi+openmp_dir/run.sh
> +mpirun ./hybrid_pi ${@}
> disable that shellcheck case

Fixed, but I don't see any automated shellcheck check here.

2024-11-29 15:38 UTC, ikirker approved these changes

2024-11-29 15:38 UTC, merged